version: '3'
services:
  tinyfilemanager:
    image: 530353222/tinyfilemanager:2.4.1
    container_name: dapps-tinyfilemanager
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ${SOURCE_DIR}:/var/www/html
    restart: always